resources:
  pipelines:
  - pipeline: azure-pipelines
  repositories:
  - repository: azure pipelines  # identifier (A-Z, a-z, 0-9, and underscore)
    type: git  # see the following "Type" topic
    name: azure-pipelines  # repository name (format depends on `type`)
