parameters:
- name: branch
  type: string
  
jobs:
- job: containerize_master
  steps:
  - bash: echo ${{ parameters.branch }}
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

- job: containerize_development
  steps:
  - bash: echo ${{ parameters.branch }}
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/development'))