parameters:
- name: branch
  type: string
  
jobs:
- job: containerize master
  steps:
  - bash: echo ${{ parameters.branch }}
  condition: and(succeeded(), eq(variables['branch'], 'refs/heads/master'))

- job: containerize development
  steps:
    - bash: echo ${{ parameters.branch }}
    condition: and(succeeded(), eq(variables['branch'], 'refs/heads/development'))